name: Test runner

on:
  push:
    branches:
      - main

jobs:
  test-runner:
    runs-on:
      - self-hosted
      - windows
      - x64
    steps:
      - name: Verif
        run: echo "Verif"

      - name: tests de commandes
        run: |
          echo "Local runner OK"
          hostname
          whoami
          uname -a